### ISSUE TITLE
Search Optimization Question

### ISSUE THREAD

**Issue by serkandyck** [ezekielchentnik/preact-pwa#7]
i try using this project needed heavly SEO web app. i checked google on  demo site https://preact-pwa.appspot.com/ on indexed google page . with site:https://preact-pwa.appspot.com/ some articles page missed and about page too. if i checked body tag on article page or about page html not rendered only show home page rendered page. can i use this starter for my SEO needed web app ?

**Comment by ezekielchentnik** [comment]
@SerkanDayicik take a look at this closed issue, it may help answer your question (specifically the part about the escape hatch, incrase the threshold time to ensure always SSR):

https://github.com/ezekielchentnik/preact-pwa/issues/2

I'm also working on adding in 'prerender' so that there is an option to do SSR w/escape hatch, full blown SPA (render only on client), or prerender (generating static html, like SSR, but at build time).

I'll likely be able to push up some of the prerender stuff this week.

Cheers!
